package fi.jenniriikonen.playbank.domain;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.sun.istack.NotNull;



@Entity

public class Category {
	//Autogenerated id
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private long categoryid;
	private String name;
	
	//Constructors
	public Category() {
	}

	public Category(String name) {
		super();
		this.name = name;
	}
	
	//Need for REST to work
	@JsonBackReference
	//Database connections
	//One to many mapped by category to Play. 
	//Attribute is list hence one category may include many plays
	@OneToMany(cascade = CascadeType.ALL, mappedBy = "category")
	private List<Play> plays;
		
	//Getters and setters	
	public long getCategoryid() {
		return categoryid;
	}

	public void setCategoryid(long categoryid) {
		this.categoryid = categoryid;
	}

	public List<Play> getPlays() {
		return plays;
	}

	public void setPlays(List<Play> plays) {
		this.plays = plays;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Override
	public String toString() {
		return "Category [categoryid=" + categoryid + ", name=" + name + ", plays=" + plays + "]";
	}


	
	
}
