package fi.jenniriikonen.playbank.domain;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.validation.constraints.Min;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.sun.istack.NotNull;



@Entity 

public class Play {
	//Autogenerated id
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)

	private long id;
	@Size(min=3, max=30)
	private String title;
	@Size(min=5, max=250)
	private String description;
	@Min(1)
	private int playersmincount;
	@NotNull
	private int palyerminage;
	
	//Constructors
	public Play() {
	}
	
	public Play(String title, String description, int playersmincount, int palyerminage, Category category) {
		super();
		this.title = title;
		this.description = description;
		this.playersmincount = playersmincount;
		this.palyerminage = palyerminage;
		this.category = category;
	}
	
	//Database connections
	//Joining category table to play-table
	@ManyToOne
	//Need for REST to work
	@JsonBackReference
	@JoinColumn(name =  "categoryid")
	private Category category;
	

	//Getters and setters
	
	
	public String getTitle() {
		return title;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getPlayersmincount() {
		return playersmincount;
	}

	public void setPlayersmincount(int playersmincount) {
		this.playersmincount = playersmincount;
	}

	public int getPalyerminage() {
		return palyerminage;
	}

	public void setPalyerminage(int palyerminage) {
		this.palyerminage = palyerminage;
	}
	
	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}


	@Override
	public String toString() {
		return "Play [title=" + title + ", description=" + description + ", playersmincount=" + playersmincount
				+ ", palyerminage=" + palyerminage + "]";
	}
	
	

}
